x-environment:
  &default-env
  SERVER_NAME: "Prominence II RPG: Hasturian Era"
  ALLOW_FLIGHT: "TRUE"
  ENABLE_ROLLING_LOGS: "TRUE"
  TZ: "MSK"
  INIT_MEMORY: "4G"
  MEMORY: "8G"
  EULA: "TRUE"
  TYPE: "MODRINTH"
  MODRINTH_LOADER: "fabric"
  MODRINTH_MODPACK: "EGs3lC8D"
  MODRINTH_OVERRIDES_EXCLUSIONS: |
    shaderpacks/**
  MODS_FILE: /server-config/mods.txt
  GUI: "FALSE"
  USE_SIMD_FLAGS: "TRUE"
  PLAYER_IDLE_TIMEOUT: "600"

networks:
  mc-network:
    driver: bridge    
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    networks:
      mc-network:
        ipv4_address: 172.21.0.2
    restart: unless-stopped
    volumes:
      - data:/server:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "25565:25565"

  mc:
    image: itzg/minecraft-server:java21-graalvm
    networks:
      mc-network:
        ipv4_address: 172.21.0.3
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc
      - lazymc.server.address=mc:25565
      - lazymc.public.version=1.20.1
    tty: true
    stdin_open: true
    restart: no
    depends_on:
      - drasl
    environment:
      <<: *default-env
      JAVA_TOOL_OPTIONS: >-
        -Dminecraft.api.env=custom
        -Dminecraft.api.auth.host=http://172.21.0.4:25585/auth
        -Dminecraft.api.account.host=http://172.21.0.4:25585/account
        -Dminecraft.api.session.host=http://172.21.0.4:25585/session
        -Dminecraft.api.services.host=http://172.21.0.4:25585/services
    volumes:
      - data:/data
      - minecraft-world:/data/world
      - ./server-config:/server-config:ro
      - ./third_party/mods/ftb-library-fabric-2001.1.4.jar:/data/mods/ftb-library-fabric-2001.1.4.jar:ro
      - ./third_party/mods/ftb-quests-fabric-2001.2.0.jar:/data/mods/ftb-quests-fabric-2001.2.0.jar:ro
      - ./third_party/mods/ftb-teams-fabric-2001.1.4.jar:/data/mods/ftb-teams-fabric-2001.1.4.jar:ro

  drasl:
    image: unmojang/drasl
    networks:
      mc-network:
        ipv4_address: 172.21.0.4
    volumes:
      - drasl-data:/var/lib/drasl
      - ./drasl-config:/etc/drasl
    ports:
      - "25585:25585"

volumes:
  data:
  drasl-data:
  minecraft-world: